### ISSUE TITLE
nil DNU #isBlockNode from PPFormatter >> #needsParenthesisFor:

### ISSUE THREAD

**Issue by LinqLover** [tom95/poppy-print#3]
Occurs reproducibly when pretty-printing Object>>compositeAnimations (part of hpi-swa/animations).

<details>
<pre><code>10 March 2021 4:42:27.56515 pm

VM: Win32 - Smalltalk
Image: Squeak6.0alpha [latest update: #20249]

SecurityManager state:
Restricted: false
FileAccess: true
SocketAccess: true
Working Dir C:\Users\Christoph\OneDrive\Dokumente\Squeak
Trusted Dir C:\Users\Christoph\OneDrive\Dokumente\Squeak\Christoph
Untrusted Dir C:\Users\Christoph\OneDrive\Dokumente\My Squeak

UndefinedObject (Object) >> #doesNotUnderstand: #isBlockNode
	Receiver: nil
	Arguments and temporary variables: 
		aMessage: 	isBlockNode
		exception: 	MessageNotUnderstood: UndefinedObject>>isBlockNode
		resumeValue: 	nil
	Receiver's instance variables: 
nil

PPFormatter >> #needsParenthesisFor:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{registry := AnimAnimationRegistry value}
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

PPFormatter >> #visitNode:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{registry := AnimAnimationRegistry value}
		needsParens: 	nil
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

PPFormatter >> #visitMessageNode:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{(registry := AnimAnimationRegistry value) == nil}
		multiLine: 	nil
		isInCascade: 	false
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

MessageNode >> #accept:
	Receiver: {(registry := AnimAnimationRegistry value) == nil}
	Arguments and temporary variables: 
		aVisitor: 	a PPFormatter
	Receiver's instance variables: 
		comment: 	nil
		pc: 	nil
		receiver: 	{registry := AnimAnimationRegistry value}
		selector: 	{==}
		precedence: 	2
		special: 	0
		arguments: 	{{nil}}
		sizes: 	#(nil)
		equalNode: 	nil
		caseErrorNode: 	nil
		originalReceiver: 	{registry := AnimAnimationRegistry value}
		originalSelector: 	#==
		originalArguments: 	{{nil}}

[] in PPFormatter >> #preFormat:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{(registry := AnimAnimationRegistry value) == nil}
		formatter: 	{a PPFormatter}
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

FullBlockClosure >> #cull:
	Receiver: [closure] in PPFormatter >> #preFormat:
	Arguments and temporary variables: 
		firstArg: 	{(registry := AnimAnimationRegistry value) == nil}
	Receiver's instance variables: 
		outerContext: 	PPFormatter >> #preFormat:
		startpcOrMethod: 	([] in PPFormatter>>#preFormat: "a CompiledBlock(3847756)")
		numArgs: 	0
		receiver: 	a PPFormatter

[] in Dictionary >> #at:ifAbsentPut:
	Receiver: a Dictionary()
	Arguments and temporary variables: 
		key: 	{(registry := AnimAnimationRegistry value) == nil}
		aBlock: 	[closure] in PPFormatter >> #preFormat:
	Receiver's instance variables: 
		tally: 	0
		array: 	#(nil nil nil nil nil)

Dictionary >> #at:ifAbsent:
	Receiver: a Dictionary()
	Arguments and temporary variables: 
		key: 	{(registry := AnimAnimationRegistry value) == nil}
		aBlock: 	[closure] in Dictionary >> #at:ifAbsentPut:
	Receiver's instance variables: 
		tally: 	0
		array: 	#(nil nil nil nil nil)

Dictionary >> #at:ifAbsentPut:
	Receiver: a Dictionary()
	Arguments and temporary variables: 
		key: 	{(registry := AnimAnimationRegistry value) == nil}
		aBlock: 	[closure] in PPFormatter >> #preFormat:
	Receiver's instance variables: 
		tally: 	0
		array: 	#(nil nil nil nil nil)

PPFormatter >> #preFormat:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{(registry := AnimAnimationRegistry value) == nil}
		formatter: 	{a PPFormatter}
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

PPFormatter >> #willBeMultiLine:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{(registry := AnimAnimationRegistry value) == nil}
		text: 	nil
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

[] in PPFormatter >> #isMultiLineMessage:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
<<error during printing>
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

[] in OrderedCollection (Collection) >> #anySatisfy:
	Receiver: an OrderedCollection({(registry := AnimAnimationRegistry value) == nil} {[#()]})
	Arguments and temporary variables: 
		aBlock: 	{(registry := AnimAnimationRegistry value) == nil}
		each: 	[closure] in PPFormatter >> #isMultiLineMessage:
	Receiver's instance variables: 
		array: 	{{(registry := AnimAnimationRegistry value) == nil} . {[#()]}}
		firstIndex: 	1
		lastIndex: 	2

OrderedCollection >> #do:
	Receiver: an OrderedCollection({(registry := AnimAnimationRegistry value) == nil} {[#()]})
	Arguments and temporary variables: 
		aBlock: 	[closure] in OrderedCollection (Collection) >> #anySatisfy:
		index: 	1
	Receiver's instance variables: 
		array: 	{{(registry := AnimAnimationRegistry value) == nil} . {[#()]}}
		firstIndex: 	1
		lastIndex: 	2

OrderedCollection (Collection) >> #anySatisfy:
	Receiver: an OrderedCollection({(registry := AnimAnimationRegistry value) == nil} {[#()]})
	Arguments and temporary variables: 
		aBlock: 	[closure] in PPFormatter >> #isMultiLineMessage:
	Receiver's instance variables: 
		array: 	{{(registry := AnimAnimationRegistry value) == nil} . {[#()]}}
		firstIndex: 	1
		lastIndex: 	2

PPFormatter >> #isMultiLineMessage:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{AnimAnimationRegistry value
	ifNil: [#()]
	ifNotNil: [:registry | regis...etc...
		relevantParts: 	an OrderedCollection({(registry := AnimAnimationRegistry value) ...etc...
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

PPFormatter >> #visitMessageNode:
	Receiver: a PPFormatter
	Arguments and temporary variables: 
		aNode: 	{AnimAnimationRegistry value
	ifNil: [#()]
	ifNotNil: [:registry | regis...etc...
		multiLine: 	nil
		isInCascade: 	false
	Receiver's instance variables: 
		stream: 	a WriteStream
		indent: 	1
		parents: 	a Dictionary({[#()]}->{AnimAnimationRegistry value
	ifNil: [#()]
	ifNo...etc...
		preFormatCache: 	a Dictionary()
		comments: 	an OrderedCollection()

MessageNode >> #accept:
	Receiver: {AnimAnimationRegistry value
	ifNil: [#()]
	ifNotNil: [:registry | registry compositeAnimations...etc...
	Arguments and temporary variables: 
		aVisitor: 	a PPFormatter
	Receiver's instance variables: 
		comment: 	nil
		pc: 	nil
		receiver: 	{(registry := AnimAnimationRegistry value) == nil}
		selector: 	{ifTrue:ifFalse:}
		precedence: 	3
		special: 	17
		arguments: 	an OrderedCollection({[#()]} {[:registry | registry compositeAnimations...etc...
		sizes: 	#(nil nil)
		equalNode: 	nil
		caseErrorNode: 	nil
		originalReceiver: 	{AnimAnimationRegistry value}
		originalSelector: 	#ifNil:ifNotNil:
		originalArguments: 	an OrderedCollection({[#()]} {[:registry | registry compositeAnimations...etc...

--- The full stack ---
UndefinedObject (Object) >> #doesNotUnderstand: #isBlockNode
PPFormatter >> #needsParenthesisFor:
PPFormatter >> #visitNode:
PPFormatter >> #visitMessageNode:
MessageNode >> #accept:
[] in PPFormatter >> #preFormat:
FullBlockClosure >> #cull:
[] in Dictionary >> #at:ifAbsentPut:
Dictionary >> #at:ifAbsent:
Dictionary >> #at:ifAbsentPut:
PPFormatter >> #preFormat:
PPFormatter >> #willBeMultiLine:
[] in PPFormatter >> #isMultiLineMessage:
[] in OrderedCollection (Collection) >> #anySatisfy:
OrderedCollection >> #do:
OrderedCollection (Collection) >> #anySatisfy:
PPFormatter >> #isMultiLineMessage:
PPFormatter >> #visitMessageNode:
MessageNode >> #accept:
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[] in PPFormatter >> #visitNode:
Dictionary >> #at:ifPresent:ifAbsent:
PPFormatter >> #visitNode:
PPFormatter >> #visitReturnNode:
ReturnNode >> #accept:
[] in PPFormatter >> #visitNode:
Dictionary >> #at:ifPresent:ifAbsent:
PPFormatter >> #visitNode:
[] in [] in PPFormatter >> #visitBlockNode:
OrderedCollection >> #do:
[] in PPFormatter >> #visitBlockNode:
PPFormatter >> #indent:around:
PPFormatter >> #visitBlockNode:
BlockNode >> #accept:
[] in PPFormatter >> #visitNode:
Dictionary >> #at:ifPresent:ifAbsent:
PPFormatter >> #visitNode:
[] in PPFormatter >> #visitMethodNode:
PPFormatter >> #indent:around:
PPFormatter >> #visitMethodNode:
MethodNode >> #accept:
PPFormatter class >> #formatString:class:noPattern:notifying:
PPFormatter class >> #format:in:notifying:
Browser (CodeHolder) >> #sourceStringPrettifiedAndDiffed
Browser >> #selectedMessage
[] in Browser >> #contents
[] in Browser (CodeHolder) >> #editContentsWithDefault:
Dictionary >> #at:ifAbsent:
Browser (CodeHolder) >> #editContentsWithDefault:
Browser >> #contents
PluggableTextMorphPlus (PluggableTextMorph) >> #getText
PluggableTextMorphPlus (PluggableTextMorph) >> #update:
PluggableTextMorphPlus >> #update:
[] in Browser (Object) >> #changed:
DependentsArray >> #do:
Browser (Object) >> #changed:
Browser >> #changed:
Browser (Object) >> #contentsChanged
Browser (CodeHolder) >> #contentsChanged
Browser (CodeHolder) >> #togglePrettyPrint
Browser (CodeHolder) >> #setContentsSymbol:
PluggableDropDownListMorph >> #basicSelection:
-- and more not shown --</code></pre></details>

**Comment by stlutz** [comment]
Same error in `Morph >> #doLayoutIn:`

**Comment by tom95** [comment]
Should be fixed now, please reopen if you manage to reproduce it :)

**Comment by LinqLover** [comment]
Unfortunately, still occurs on my end (just ran the install script again). Are you sure you have committed everything? 😅

**Comment by tom95** [comment]
Hmm tests on CI are green for this. What method are you currently trying it out on? Did you `get; load` the install script?

**Comment by LinqLover** [comment]
I'm very sorry for the late answer - first I had [network problems](https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/554) with my image and then I was on holiday ... Anyway: Yes, of course, I missed the `get`, now it works as well on my end! 👍

**Comment by tom95** [comment]
No problem at all, thank you for the feedback :)
